build:
  version: "4.0"

server:
  port: 8081

spring:
  application:
    name: course
  config:
    import: "optional:configserver:http://localhost:8071"
  datasource:
    url: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:6543/postgres
    username: postgres.cjzrbpemchdyhtcnhhlr
    password: 2jQAVxFze5pcUwTM
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

info:
  app:
    name: "course MS"
    description: "course MS for LMS"
    version : "1.0.0"

#old config
#build:
#  version: "4.0"
#
#server:
#  port: 8081
#
#spring:
#  application:
#    name: course
#  config:
#    import: "optional:configserver:http://localhost:8071"
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: ""
#    driverClassName: org.h2.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka : true
#    serviceUrl:
#      defaultZone: "http://localhost:8070/eureka/"
#
#info:
#  app:
#    name: "course MS"
#    description: "course MS for LMS"
#    version : "1.0.0"